apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
    - name: app-container
      image: app-store
      imagePullPolicy: Never
      ports:
        - containerPort: 5000