apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: db-container
      image: db-store
      imagePullPolicy: Never
      ports:
        - containerPort: 3306